esphome:
  name: zeroconf-example
  platform: ESP32
  board: esp-wrover-kit

wifi:
  ssid: !secret wifi_ssid
  password: !secret wifi_password

external_components:
  - source: components
#  - source:  github://thegroove/esphome-zeroconf@main

zeroconf:
  - service: tube_zb_gw_efr32
    protocol: tcp
    port: 6638
    txt:
      version: 1.0
      radio_type: ezsp
      baud_rate: 115200
      data_flow_control: software
